# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: ory

before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
    - go mod tidy
builds:
-
  binary: ory
  env:
    - CGO_ENABLED=0
  goarch:
    - amd64
    - 386
    - arm
    - arm64
  goarm:
    - 5
    - 6
    - 7
  goos:
    - freebsd
    - plan9
    - solaris
    - netbsd
    - openbsd
    - windows
    - darwin
archive:
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: 64-bit
  format_overrides:
  - goos: windows
    format: zip
  files:
    -  release/LICENSE
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: ory
    name: ory-homebrew-tap
  homepage:  https://www.ory.sh
  commit_author:
    name: ory
    email: hi@ory.sh

scoop:
  bucket:
    owner: ory
    name: ory-scoop-bucket
  homepage:  https://www.ory.sh
  commit_author:
    name: ory
    email: hi@ory.sh

#nfpm:
#  replacements:
#    amd64: 64-bit
#    386: 32-bit
#    darwin: macOS
#    linux: Linux
#  vendor: Ory Systems GmbH
#  homepage: https://www.ory.sh/
#  maintainer: Ory Systems GmbH <hi@ory.sh>
#  formats:
#  - deb
#  - rpm
